### PR TITLE
Get pretalx proposal

### PR DESCRIPTION
**Pull request by Carreau**
This is public WIP to discuss getting a pretalx instance. 

One of the question from Madicken Munk was to make sure with a yearly subscription we still per-conference configurations like tracks/tracks-name ... Which from my test is the case, each event has independant configuration.

### CODE REVIEW

**Comment by aterrel** [comment]
@numfocus/infrastructure should reach out to pretalx to get pricing before accepting

**Comment by Carreau** [comment]
yes we have a private thread on slack, and this is mostly to refine the
proposal in a public place.

dutc, james, I and Mridul talked about it in person.

**Comment by Carreau** [comment]
Is there any update on this, should we push, or close ?

**Comment by vchuravy** [comment]
Just chiming in, we (JuliaCon) have been using the hosted version of pretalx for several years. We have also productively engaged with the developer and funded some development efforts that we needed.

**Comment by mkitti** [comment]
Per Valentin's point above, we, the JuliaCon organizing committee, would be interested in pursuing the hosted version for NumFOCUS as a whole.

**Comment by Carreau** [comment]
I've pinged relevant people in slack as we discussed in person at the nf summit.

Let's move that out of drafts.

**Comment by Carreau** [comment]
This is being followed up internally mostly trying to compare the current cost to the cost of having it hosted. I don't have any number and suggested any update to be posted here.

**Comment by mkitti** [comment]
How do you factor in the support costs needed from self-hosting versus having it hosted?

**Comment by Carreau** [comment]
I'm going to make assumptions here, but I'm going to guess NF will tally up the cost they pay Martey to deploy (on EC2 I believe) + the monthly server cost, and that they will then contact Pretalx to get a price estimate and compare. I think entangling the specific costs related to pretalx from the rest might be a bit tedious and will take some time.

I personally would love to have the various current cost analysis public, but I don't have access to those, and it is not my choice to make. 

IMHO there is also a time cost for organizers and attendees that a single hosted instance for all conference (say cfp.numfocus.org) should be taken into account, but it's unclear how this will get factored in.

**Comment by aterrel** [comment]
I'm drafting a budget for the Board of Directors in the next month. Hopefully we can get the funds approved. Right now Matt is focused on internal infrastructure and the committee is still coming up to steam getting charters and project requests sorted.

**Comment by aterrel** [comment]
we have approved budgets now, will be reaching out to flesh out how we want to work together with other projects with a similar need.

**Pull request closed without merging**
