### PR TITLE
Updated Numbers at bottom of page

### PR DESCRIPTION
**Pull request by Trentonoliphant**
Numbers taken from [OpenHub.net] (http://www.OpenHub.net) on 01/22/2015, includes all projects listed on [NumFOCUS.org](Http://www.NumFOCUS.org) except inscight (Couldn't find it on the site).

### CODE REVIEW

**Comment by rgommers** [comment]
@Trentonoliphant thanks for looking into this.

Do you have a script to obtain updated numbers, or did you do this by hand? The former would be great to have, then we can simply run it once in a while to keep these numbers up to date.

**Comment by Trentonoliphant** [comment]
I just did it by hand, Leah wanted them to be updated. I can start looking at creating a script to get the numbers though, I don't have a ton of experience with writing this kind of script but I'm willing to look into it.

**Comment by rgommers** [comment]
That would be great!

**Comment by rgommers** [comment]
Which projects are responsible for the large increase in lines of code? And are the largest ones?

**Comment by Trentonoliphant** [comment]
The biggest one is the addition of python(x,y), OpenHub reports that it has almost 11 million lines of code.

**Comment by rgommers** [comment]
Ah, that makes sense. I don't think we want to report that though - Python(x,y) is a distribution so most of those 11 million lines is projects like numpy/scipy/scikits/etc that we already counted. Only the Spyder IDE and the code needed to build the distribution should be counted. The build code may be hard to separate out, but Spyder shouldn't be.

**Comment by Trentonoliphant** [comment]
Spyder has its own line count on openhub, should I just take python(x,y) out?

**Comment by rgommers** [comment]
That sounds good.

**Comment by aterrel** [comment]
Thanks for the updates! Pushing live now.

**Pull request merged**
