### PR TITLE
DOC: Public records

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by aterrel** [comment]
@rgommers this is great! is there any reason not to go ahead and push it out?

**Comment by rgommers** [comment]
The main loose end: I want to add the remaining minutes (second half of 2014) in the next few days. The other thing is a few missing documents. I need to either add them (I asked @lsilen for the originals) or remove them from the overview page.

I'm going on holiday this Saturday; aiming to finish it before then.

**Comment by aterrel** [comment]
Okay feel free to give me any tasks here and I'll try to track things down.

**Comment by rgommers** [comment]
Okay, this is good to go now. @aterrel can you give this a sanity check?

**Comment by aterrel** [comment]
All seems sane to me!

I'll merge and push live.

**Comment by aterrel** [comment]
merged at e5f64e756e430e254a88f120680a0b7bd9e36c9c

**Comment by rgommers** [comment]
@aterrel unrelated note: I'm in China, and apparently Gmail is now completely blocked. I hadn't counted on that (it always worked before in this part of the country, even when Western media said it wouldn't), so didn't set up any temporary forwarding. Looks like I won't be able to read my email for a couple of weeks. If there's anything urgent, please ping me here.

**Comment by aterrel** [comment]
@rgommers, cool have a good trip!

**Comment by rgommers** [comment]
@aterrel you missed some commits, I merged them in d466830. More importantly, I ran ``make github`` which broke the site. You've never touched the ``gh-pages`` branch, so there is now some other (undocumented?) deployment mechanism apparently. Can you have a look at this?

**Comment by aterrel** [comment]
Thanks for catching this.

My process is the same as on the readme:

```shell
$ make html
$ make serve
$ make github
```

Maybe some of the dependencies aren't as clear. I'll try to get a fresh box and try it out here in a bit.

**Comment by aterrel** [comment]
I guess I should say, `make github` does a forced update which overwrites the previous commits. Also you have to name this repo as upstream.

**Comment by rgommers** [comment]
I do have it named ``upstream`` and ``make html`` + ``make serve`` works fine locally. But still ``make github`` doesn't. Looking at ``upstream/gh-pages`` the diff of the last commit is huge. Maybe due to missing dependencies, but probably also something else that you have locally?

**Pull request closed without merging**
