### PR TITLE
add QuantEcon to projects

### PR DESCRIPTION
**Pull request by dutc**
Simple draft adding QuantEcon to listed projects.

### CODE REVIEW

**Comment by rgommers** [comment]
Looks good to me. There's a merge conflict here that needs resolving though.

**Comment by rgbkrk** [comment]
This PR can probably be closed since the site is now on weebly.

/cc @cc7768

**Comment by cc7768** [comment]
...

**Comment by rgommers** [comment]
Thanks. yes, should have been closed a long time ago. QuantEcon is on the list of sponsored projects at http://www.numfocus.org/open-source-projects.html

**Pull request closed without merging**
